### ISSUE TITLE
How can I access the data directly without using gsutil?

### ISSUE THREAD

**Issue by slerman12** [google-research/rliable#12]
I haven't got gsutil set up on my M1 MacBook and I'm not sure the steps are super streamlined. Can I somehow access the data from my browser or download it another way?

**Comment by agarwl** [comment]
You can directly access the data using the colab mentioned in the README: [bit.ly/statistical_precipice_colab](https://bit.ly/statistical_precipice_colab) or by accessing the public GCP bucket here (you'd  need to sign in with your gmail account to use Gcloud) :  https://console.cloud.google.com/storage/browser/rl-benchmark-data.
