### ISSUE TITLE
Colab is broken

### ISSUE THREAD

**Issue by ezhang7423** [google-research/rliable#16]
Seems like all the code cells are missing from [bit.ly/statistical_precipice_colab](https://colab.research.google.com/drive/1a0pSD-1tWhMmeJeeoyZM1A-HCW3yf1xR?usp=sharing).
![image](https://user-images.githubusercontent.com/54998055/181925113-3ffd2931-81f1-498c-8efd-88a74fa02f46.png)

**Comment by agarwl** [comment]
Sorry for the inconvenience, I've fixed the colab now.

**Comment by ezhang7423** [comment]
Thank you!
