### ISSUE TITLE
Package issue:

### ISSUE THREAD

**Issue by xkianteb** [google-research/rliable#2]
The package structure is messed up when attempting to install the code from the GitHub repo using "pip install -e ." In particular the problem is that the package name is "rliable" but "rliable" is not a folder in the repo. To fix this you need to create a folder and move all the python files inside it i.e.

[1] Create a folder called rliable

[2] Then move all the *.py files inside this folder. Below is the what the new folder structure would look like.

CITATION.bib
CONTRIBUTING.md
images/
LICENSE
README.md
setup.py
rliable/
    - metrics.py
    - library.py
    - test
    - __init__.py

Making this change allows me to be able to run "from rliable import library" successfully.

**Comment by agarwl** [comment]
Thanks for pointing this out :) Fixed now.
