### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by MischaPanch** [google-research/rliable#26]
@agarwl Could you please make a release of the current state to pypi? Unfortunately, [pypi doesn't permit git dependencies](https://github.com/python-poetry/poetry/issues/4471), so the fixes to dependencies by @araffin and me in the last months don't come into effect for libraries that depend on rliable.

I wanted to release a new version of Tianshou that uses rliable for evaluations, but I can't do it because of this. Would really appreciate if you could create a new release of rliable soon, as otherwise I'd be forced to release a fork or something like that to be able to publish the package.

@Trinkle23897 FYI

**Comment by agarwl** [comment]
I am sparsely maintaining this -- I am happy to make you an owner of the PyPI repo, would that work? If so, please share your email here.

**Comment by agarwl** [comment]
CC @psc-g -- can you help with this? Might be much faster for you to figure this out.

**Comment by MischaPanch** [comment]
Yes, that would work, thanks! I'll make a PR here as well to bump the version and pin the version of pandas (wouldn't build without it)

My mail is mischa.panch@gmail.com, on pypi my username is MischaPanch (like in github)

Are you up for reviewing an occasional PR? Otherwise it might make sense to continue maintenance in a fork (I guess it's not possible to make non-google people into owners)

**Comment by MischaPanch** [comment]
I have meanwhile released my fork, just to not be blocked by it. It's here:

https://pypi.org/project/rliable-fork/

**Comment by agarwl** [comment]
Yes, happy to review occasional pr. just send an email to rishabhagarwal@google.com if urgent. 

I have also sent an invite for adding you as a maintainer of the Pypi project. Hopefully, this can speed up future releases.

**Comment by MischaPanch** [comment]
Awesome, thank you! And really appreciate the work you put into the repo (and the paper), wish there'd be more things like that instead of ever-more brittle and unusable algorithms.

**Comment by MischaPanch** [comment]
Done, I released the current state of master as 1.1.0 to pypi, closing this

**Comment by agarwl** [comment]
Awesome, thanks for the help!
