### ISSUE TITLE
Downloading data set always stuck 

### ISSUE THREAD

**Issue by HYDesmondLiu** [google-research/rliable#3]
Thanks for sharing the repo. 
There is a problem that every time I download the dataset, it is always stuck somewhere at 9X%
Do you know what might cause this?

```
...
Copying gs://rl-benchmark-data/atari_100k/SimPLe.json...
Copying gs://rl-benchmark-data/atari_100k/OTRainbow.json...
[55/59 files][  2.9 MiB/  3.0 MiB]  98% Done
```

**Comment by agarwl** [comment]
I haven't faced this issue before (maybe try a different internet connection) .. ran the data download code just now in the colab: https://colab.research.google.com/drive/1BtLeT-zO_WSFuelOu4Km14HzZ-TVMogv?usp=sharing and it seemed to be download 100% data.

**Comment by HYDesmondLiu** [comment]
Thanks for the prompt reply. I will try it later.
