### ISSUE TITLE
Urgent question about data aggregates

### ISSUE THREAD

**Issue by slerman12** [google-research/rliable#4]
Hi, we compiled the Atari 100k results from DrQ, CURL, and DER, and the mean/median human-norm scores are well below those reported in prior works, including from co-authors of the rliable paper. 

We have median human-norm scores all around 0.10 - 0.12.

Is this accurate? Of all of these, DER (the oldest of the algs) has the highest mean human-norm score.

**Comment by agarwl** [comment]
That doesn't seem right -- the aggregate scores should match as in figure below (uses 10 runs), which can be done using the colab at [bit.ly/statistical_precipice_colab](htttps://bit.ly/statistical_precipice_colab):

![image](https://user-images.githubusercontent.com/12142945/142565616-cce826e3-f659-49af-a657-7684c4f9b321.png).
